version: "3"
services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php83-service
    networks:
      - nginx-php83
  php83-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php83-container
    ports:
      - "9103:9003"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php83
networks:
  nginx-php83:
